sudo: required

language: csharp
matrix:
  include:
    - os: linux
      dotnet: none
      mono: none
      dist: trusty
    - os: osx
      osx_image: xcode8.2
      language: generic
before_install:
  - ./.travis/before-install-$TRAVIS_OS_NAME.sh

script:
  - dotnet restore ./LiteDB/LiteDB.dotnet.csproj
  - dotnet build ./LiteDB/LiteDB.dotnet.csproj
  - dotnet restore ./LiteDB.Tests/LiteDB.Tests.dotnet.csproj
  - dotnet build ./LiteDB.Tests/LiteDB.Tests.dotnet.csproj
  - dotnet test ./LiteDB.Tests/LiteDB.Tests.dotnet.csproj --logger:console;verbosity=normal

